/*
 Copyright (c) 2019. Vladimir Ulitin, Partners Healthcare and members of Forome Association

 Developed by Vladimir Ulitin <v.ulitin@mobin.me>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

	 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

node {

	try {

		stage('init') {
			echo 'Initializing...'

			def docker = tool name: 'docker-17.09.0-ce'
			env.PATH = "${docker}:${env.PATH}"
		}

		stage('clean workspace & checkout') {
			deleteDir()
			checkout scm
		}

		stage('Build & Publish docker image') {
		    sh("echo -n \"${params.DOCKERHUB_PASSWORD}\" | docker login --username ${params.DOCKERHUB_LOGIN} --password-stdin ${params.DOCKERHUB}")

			def image = "${params.DOCKERHUB}/forome/ensembl-vep:latest";
			sh("docker build . -t ${image} --file pipeline/projects/ensembl-vep/Dockerfile")
			sh("docker push ${image}")
		}

	} catch (Throwable e) {
		throw e
	}

}
